-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 10, 2025 at 08:24 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `scheme_finder_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `schemes`
--

CREATE TABLE `schemes` (
  `id` int(11) NOT NULL,
  `scheme_name_en` varchar(255) NOT NULL,
  `scheme_name_hi` varchar(255) NOT NULL,
  `scheme_name_mr` varchar(255) NOT NULL,
  `description_en` text DEFAULT NULL,
  `description_hi` text DEFAULT NULL,
  `description_mr` text DEFAULT NULL,
  `benefits_en` text DEFAULT NULL,
  `benefits_hi` text DEFAULT NULL,
  `benefits_mr` text DEFAULT NULL,
  `application_link` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `schemes`
--

INSERT INTO `schemes` (`id`, `scheme_name_en`, `scheme_name_hi`, `scheme_name_mr`, `description_en`, `description_hi`, `description_mr`, `benefits_en`, `benefits_hi`, `benefits_mr`, `application_link`, `created_at`) VALUES
(1, 'Pradhan Mantri Jan Dhan Yojana', 'प्रधानमंत्री जन धन योजना', 'प्रधानमंत्री जन धन योजना', 'A national mission for financial inclusion to ensure access to financial services like banking, savings, deposit accounts, remittance, credit, insurance, pension in an affordable manner.', 'वित्तीय समावेशन के लिए एक राष्ट्रीय मिशन, जिसमें बैंकिंग, बचत, जमा खाते, प्रेषण, ऋण, बीमा, पेंशन जैसी वित्तीय सेवाओं तक सस्ती पहुंच सुनिश्चित करना शामिल है।', 'आर्थिक समावेशनासाठी एक राष्ट्रीय अभियान, ज्यात बँकिंग, बचत, ठेवी खाती, प्रेषण, कर्ज, विमा, निवृत्ती वेतन यासारख्या आर्थिक सेवांपर्यंत परवडणाऱ्या दरात पोहोच सुनिश्चित करणे समाविष्ट आहे.', 'Basic Savings Bank Deposit Account, RuPay Debit Card, Accidental Insurance cover of Rs. 2 Lakh, Overdraft facility.', 'मूलभूत बचत बँक ठेव खाते, रुपे डेबिट कार्ड, 2 लाख रुपये पर्यंतचा अपघाती विमा, ओव्हरड्राफ्ट सुविधा।', 'मूलभूत बचत बँक ठेव खाते, रुपे डेबिट कार्ड, 2 लाख रुपयांपर्यंतचा अपघात विमा, ओव्हरड्राफ्ट सुविधा.', 'https://pmjdy.gov.in/', '2025-06-10 05:03:26'),
(2, 'Pradhan Mantri Ujjwala Yojana', 'प्रधानमंत्री उज्ज्वला योजना', 'प्रधानमंत्री उज्ज्वला योजना', 'A scheme to provide LPG connections to women from Below Poverty Line (BPL) households.', 'गरीबी रेखा से नीचे (बीपीएल) के परिवारों की महिलाओं को एलपीजी कनेक्शन प्रदान करने की एक योजना।', 'दारिद्र्यरेषेखालील (बीपीएल) कुटुंबातील महिलांना एलपीजी कनेक्शन प्रदान करण्याची एक योजना.', 'Free LPG connection, financial assistance for gas stove and first refill.', 'मुफ्त एलपीजी कनेक्शन, गैस स्टोव और पहले रिफिल के लिए वित्तीय सहायता।', 'मोफत एलपीजी कनेक्शन, गॅस स्टोव्ह आणि पहिल्या रिफिलसाठी आर्थिक मदत.', 'https://pmuy.gov.in/', '2025-06-10 05:03:26'),
(3, 'Atal Pension Yojana', 'अटल पेंशन योजना', 'अटल पेन्शन योजना', 'A pension scheme for workers in the unorganized sector. Subscribers would receive a fixed pension based on their contribution.', 'असंगठित क्षेत्र के श्रमिकों के लिए एक पेंशन योजना। ग्राहक अपने योगदान के आधार पर एक निश्चित पेंशन प्राप्त करेंगे।', 'असंघटित क्षेत्रातील कामगारांसाठी एक निवृत्ती वेतन योजना. सदस्य त्यांच्या योगदानावर आधारित निश्चित निवृत्ती वेतन प्राप्त करतील.', 'Fixed pension of Rs. 1,000 to Rs. 5,000 per month after 60 years of age.', '60 वर्ष की आयु के बाद प्रति माह 1,000 रुपये से 5,000 रुपये तक की निश्चित पेंशन।', '60 वर्षांनंतर दरमहा रु. 1,000 ते रु. 5,000 पर्यंतचे निश्चित निवृत्ती वेतन.', 'https://www.npscra.nsdl.co.in/aty.php', '2025-06-10 05:03:26'),
(4, 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)', 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा)', 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार हमी अधिनियम (मनरेगा)', 'It aims to enhance livelihood security in rural areas by providing at least 100 days of wage employment in a financial year to every household whose adult members volunteer to do unskilled manual work.', 'यह ग्रामीण क्षेत्रों में आजीविका सुरक्षा बढ़ाने के लिए है, जिसमें प्रत्येक ऐसे परिवार के वयस्क सदस्यों को एक वित्तीय वर्ष में कम से कम 100 दिनों का मजदूरी रोजगार प्रदान किया जाता है जो अकुशल शारीरिक कार्य करने के लिए स्वेच्छा से आगे आते हैं।', 'ग्रामीण भागातील उपजीविकेची सुरक्षा वाढवणे हे या कायद्याचे उद्दीष्ट आहे, ज्यामध्ये प्रत्येक कुटुंबातील प्रौढ सदस्यांना एका आर्थिक वर्षात किमान 100 दिवसांचे वेतन रोजगार पुरवले जाते, जे निरक्षर शारीरिक काम करण्यास स्वेच्छेने पुढे येतात.', 'Guaranteed 100 days of wage employment in a financial year.', 'एक वित्तीय वर्ष में 100 दिनों के वेतन रोजगार की गारंटी।', 'एका आर्थिक वर्षात 100 दिवसांच्या वेतन रोजगाराची हमी.', 'https://nrega.nic.in/', '2025-06-10 05:03:26'),
(5, 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)', 'प्रधानमंत्री आवास योजना - ग्रामीण (पीएमएवाई-जी)', 'प्रधानमंत्री आवास योजना - ग्रामीण (पीएमएवाय-जी)', 'A social welfare flagship programme of the Indian Government to provide housing for all rural people.', 'भारत सरकार का एक सामाजिक कल्याण प्रमुख कार्यक्रम जिसका उद्देश्य सभी ग्रामीण लोगों को आवास प्रदान करना है।', 'भारतीय सरकारचा एक महत्त्वाकांक्षी सामाजिक कल्याण कार्यक्रम ज्याचा उद्देश सर्व ग्रामीण लोकांना घरे उपलब्ध करून देणे आहे.', 'Financial assistance for construction of houses, convergence with other schemes for basic amenities.', 'घरों के निर्माण के लिए वित्तीय सहायता, बुनियादी सुविधाओं के लिए अन्य योजनाओं के साथ अभिसरण।', 'घरांच्या बांधकामासाठी आर्थिक मदत, मूलभूत सुविधांसाठी इतर योजनांशी समन्वय.', 'https://pmayg.nic.in/', '2025-06-10 05:03:26'),
(6, 'Ladki Bahin Yojna', 'लाडकी बहिन योजना', 'लाडकी बहिन योजना', 'A welfare scheme aimed at supporting girls and women by providing financial assistance for education, health, and empowerment.', 'बालिकाओं और महिलाओं को शिक्षा, स्वास्थ्य और सशक्तिकरण के लिए वित्तीय सहायता प्रदान करने वाली एक कल्याणकारी योजना।', 'मुली आणि महिलांसाठी शिक्षण, आरोग्य आणि सक्षमीकरणासाठी आर्थिक मदत देणारी कल्याणकारी योजना.', 'Financial aid for girl child education, healthcare support, and subsidies for skill development.', 'बालिका शिक्षा के लिए वित्तीय सहायता, स्वास्थ्य सेवा समर्थन, और कौशल विकास के लिए सब्सिडी।', 'मुलींच्या शिक्षणासाठी आर्थिक मदत, आरोग्य सेवा समर्थन, आणि कौशल्य विकासासाठी अनुदान.', 'https://www.ladkibahinyojana.co.in/', '2025-06-10 05:57:33'),
(7, 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)', 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाई)', 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाय)', 'World’s largest health insurance scheme fully financed by the government that aims to provide a health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.', 'दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना जो सरकार द्वारा पूरी तरह से वित्तपोषित है, जिसका उद्देश्य द्वितीयक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर प्रदान करना है।', 'जगातील सर्वात मोठी आरोग्य विमा योजना जी शासनाद्वारे पूर्णपणे वित्तपुरवठा केली जाते, ज्याचा उद्देश द्वितीयक आणि तृतीयक काळजीसाठी प्रति कुटुंब प्रति वर्ष 5 लाख रुपयांचे आरोग्य कवच प्रदान करणे आहे.', 'Health cover of Rs. 5 lakhs per family per year, cashless access to healthcare services.', 'प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर, स्वास्थ्य सेवाओं तक कैशलेस पहुंच।', 'प्रति कुटुंब प्रति वर्ष 5 लाख रुपयांचे आरोग्य कवच, आरोग्य सेवांसाठी कॅशलेस प्रवेश.', 'https://pmjay.gov.in/', '2025-06-10 06:04:39'),
(8, 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)', 'प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)', 'प्रधानमंत्री किसान सन्मान निधी (पीएम-किसान)', 'An initiative by the Government of India to provide income support to all eligible farmer families across the country.', 'भारत सरकार द्वारा देश भर के सभी पात्र किसान परिवारों को आय सहायता प्रदान करने की एक पहल।', 'भारत सरकारची देशभरातील सर्व पात्र शेतकरी कुटुंबांना उत्पन्न समर्थन प्रदान करण्याची एक पहल.', 'Financial benefit of Rs. 6,000 per year in three equal installments of Rs. 2,000 each.', 'प्रति वर्ष 6,000 रुपये का वित्तीय लाभ, 2,000 रुपये की तीन समान किस्तों में।', 'प्रति वर्ष 6,000 रुपयांचा आर्थिक लाभ, प्रत्येक 2,000 रुपयांच्या तीन समान हप्त्यांमध्ये.', 'https://pmkisan.gov.in/', '2025-06-10 06:04:39'),
(9, 'Stand-Up India Scheme', 'स्टैंड-अप इंडिया योजना', 'स्टँड-अप इंडिया योजना', 'Facilitates bank loans between Rs 10 lakh and Rs 1 crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.', 'कम से कम एक अनुसूचित जाति (एससी) या अनुसूचित जनजाति (एसटी) उधारकर्ता और प्रति बैंक शाखा में कम से कम एक महिला उधारकर्ता को नई उद्यम स्थापित करने के लिए 10 लाख रुपये से 1 करोड़ रुपये के बीच बैंक ऋण की सुविधा प्रदान करता है।', 'नवीन उद्योग सुरू करण्यासाठी प्रत्येक बँक शाखेत किमान एक अनुसूचित जाती (एससी) किंवा अनुसूचित जमाती (एसटी) कर्जदार आणि किमान एक महिला कर्जदार यांना 10 लाख ते 1 कोटी रुपयांपर्यंतचे बँक कर्ज सुलभ करते.', 'Bank loans for greenfield projects, focus on SC/ST and women entrepreneurs.', 'नए परियोजनाओं के लिए बैंक ऋण, एससी/एसटी और महिला उद्यमियों पर ध्यान।', 'नवीन प्रकल्पांसाठी बँक कर्ज, एससी/एसटी आणि महिला उद्योजकांवर लक्ष केंद्रित.', 'https://www.standupmitra.in/', '2025-06-10 06:04:39'),
(10, 'Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM)', 'प्रधानमंत्री श्रम योगी मान-धन (पीएम-एसवाईएम)', 'प्रधानमंत्री श्रम योगी मान-धन (पीएम-एसवायएम)', 'A voluntary and contributory pension scheme for unorganised workers.', 'असंगठित श्रमिकों के लिए एक स्वैच्छिक और अंशदायी पेंशन योजना।', 'असंघटित कामगारांसाठी एक ऐच्छिक आणि अंशदायी निवृत्ती वेतन योजना.', 'Minimum assured pension of Rs 3000 per month after attaining the age of 60 years.', '60 वर्ष की आयु प्राप्त करने के बाद प्रति माह 3000 रुपये की न्यूनतम सुनिश्चित पेंशन।', '60 वर्षांचे वय पूर्ण झाल्यावर प्रति महिना 3000 रुपयांचे किमान सुनिश्चित निवृत्ती वेतन.', 'https://maandhan.in/shramyogi', '2025-06-10 06:04:39'),
(11, 'Saur Sujala Yojana', 'सौर सुजला योजना', 'सौर सुजला योजना', 'A scheme to provide subsidized solar-powered irrigation pumps to farmers.', 'किसानों को रियायती सौर ऊर्जा संचालित सिंचाई पंप प्रदान करने की एक योजना।', 'शेतकऱ्यांना अनुदानित सौर ऊर्जा-आधारित सिंचन पंप प्रदान करण्याची एक योजना.', 'Access to reliable irrigation, reduced electricity costs, environmental benefits.', 'विश्वसनीय सिंचाई तक पहुंच, बिजली की लागत में कमी, पर्यावरणीय लाभ।', 'विश्वसनीय सिंचनासाठी प्रवेश, कमी वीज खर्च, पर्यावरणीय लाभ.', 'https://mnre.gov.in/solar/solar-pumps/', '2025-06-10 06:04:39'),
(12, 'National Food Security Act (NFSA)', 'राष्ट्रीय खाद्य सुरक्षा अधिनियम (एनएफएसए)', 'राष्ट्रीय अन्न सुरक्षा अधिनियम (एनएफएसए)', 'Aims to provide subsidized food grains to approximately two-thirds of the population.', 'जनसंख्या के लगभग दो-तिहाई हिस्से को रियायती खाद्यान्न प्रदान करना है।', 'लोकसंख्येच्या सुमारे दोन-तृतीयांश भागाला अनुदानित अन्नधान्य प्रदान करणे आहे.', 'Highly subsidized food grains (rice, wheat, coarse grains).', 'अत्यधिक रियायती खाद्यान्न (चावल, गेहूं, मोटे अनाज)।', 'अत्यंत अनुदानित अन्नधान्य (तांदूळ, गहू, भरड धान्य).', 'https://nfsa.gov.in/', '2025-06-10 06:04:39'),
(13, 'Pradhan Mantri Fasal Bima Yojana (PMFBY)', 'प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाय)', 'प्रधानमंत्री पीक विमा योजना (पीएमएफबीवाय)', 'Provides comprehensive insurance coverage against failure of crops thereby helping in stabilizing the income of farmers.', 'फसलों की विफलता के खिलाफ व्यापक बीमा कवरेज प्रदान करता है जिससे किसानों की आय को स्थिर करने में मदद मिलती है।', 'पिकांच्या नुकसानीविरुद्ध व्यापक विमा संरक्षण प्रदान करते, ज्यामुळे शेतकऱ्यांचे उत्पन्न स्थिर करण्यास मदत होते.', 'Financial support to farmers, risk mitigation for crop failure.', 'किसानों को वित्तीय सहायता, फसल विफलता के लिए जोखिम कम करना।', 'शेतकऱ्यांना आर्थिक सहाय्य, पीक नुकसानीसाठी जोखीम कमी करणे.', 'https://pmfby.gov.in/', '2025-06-10 06:04:39'),
(14, 'Skill India Mission (Pradhan Mantri Kaushal Vikas Yojana - PMKVY)', 'स्किल इंडिया मिशन (प्रधानमंत्री कौशल विकास योजना - पीएमकेवीवाय)', 'स्किल इंडिया मिशन (प्रधानमंत्री कौशल्य विकास योजना - पीएमकेवीवाय)', 'Aims to train 40 crore people in India in different skills by 2022.', '2022 तक भारत में 40 करोड़ लोगों को विभिन्न कौशलों में प्रशिक्षित करना है।', '2022 पर्यंत भारतातील 40 कोटी लोकांना विविध कौशल्यांमध्ये प्रशिक्षित करणे आहे.', 'Skill training, certification, and placement assistance.', 'कौशल प्रशिक्षण, प्रमाणन और प्लेसमेंट सहायता।', 'कौशल प्रशिक्षण, प्रमाणपत्र आणि प्लेसमेंट सहाय्य.', 'https://pmkvyofficial.org/', '2025-06-10 06:04:39'),
(15, 'National Rural Livelihoods Mission (NRLM)', 'राष्ट्रीय ग्रामीण आजीविका मिशन (एनआरएलएम)', 'राष्ट्रीय ग्रामीण उपजीविका अभियान (एनआरएलएम)', 'A poverty alleviation project implemented by the Ministry of Rural Development, Government of India. It aims at promoting self-employment and organization of rural poor into Self Help Groups (SHGs).', 'भारत सरकार के ग्रामीण विकास मंत्रालय द्वारा कार्यान्वित एक गरीबी उन्मूलन परियोजना। इसका उद्देश्य ग्रामीण गरीबों को स्वयं सहायता समूहों (एसएचजी) में स्वयं-रोजगार और संगठन को बढ़ावा देना है।', 'भारत सरकारच्या ग्रामीण विकास मंत्रालयाद्वारे कार्यान्वित केलेला एक दारिद्र्य निर्मूलन प्रकल्प. याचा उद्देश ग्रामीण गरिबांना स्वयं-रोजगार आणि स्वयं-सहायता गटांमध्ये (एसएचजी) संघटित करणे आहे.', 'Support for Self Help Groups, financial assistance, skill development for livelihood activities.', 'स्वयं सहायता समूहों के लिए समर्थन, वित्तीय सहायता, आजीविका गतिविधियों के लिए कौशल विकास।', 'स्वयं-सहायता गटांना समर्थन, आर्थिक सहाय्य, उपजीविका कार्यांसाठी कौशल्य विकास.', 'https://nrlm.gov.in/', '2025-06-10 06:04:39'),
(16, 'Swachh Bharat Abhiyan (SBA)', 'स्वच्छ भारत अभियान (एसबीए)', 'स्वच्छ भारत अभियान (एसबीए)', 'A nationwide campaign in India for the period 2014 to 2019 that aims to clean up the streets, roads, and infrastructure of India’s cities, towns, and rural areas.', '2014 से 2019 की अवधि के लिए भारत में एक राष्ट्रव्यापी अभियान जिसका उद्देश्य भारत के शहरों, कस्बों और ग्रामीण क्षेत्रों की सड़कों, सड़कों और बुनियादी ढांचे को साफ करना है।', '2014 ते 2019 या कालावधीसाठी भारतातील एक देशव्यापी मोहीम ज्याचा उद्देश भारतातील शहरे, शहरे आणि ग्रामीण भागातील रस्ते, रस्ते आणि पायाभूत सुविधा स्वच्छ करणे आहे.', 'Improved sanitation, waste management, public health benefits.', 'बेहतर स्वच्छता, अपशिष्ट प्रबंधन, सार्वजनिक स्वास्थ्य लाभ।', 'सुधारित स्वच्छता, कचरा व्यवस्थापन, सार्वजनिक आरोग्याचे फायदे.', 'https://swachhbharatmission.gov.in/', '2025-06-10 06:04:39'),
(17, 'Pradhan Mantri Gram Sadak Yojana (PMGSY)', 'प्रधानमंत्री ग्राम सड़क योजना (पीएमजीएसवाई)', 'प्रधानमंत्री ग्राम सडक योजना (पीएमजीएसवाय)', 'A nationwide plan in India to provide good all-weather road connectivity to unconnected habitations.', 'भारत में एक राष्ट्रव्यापी योजना जिसका उद्देश्य असंबंधित बस्तियों को अच्छी सभी मौसम वाली सड़क कनेक्टिविटी प्रदान करना है।', 'भारतातील एक देशव्यापी योजना ज्याचा उद्देश असंबंधित वस्त्यांना चांगली सर्व-हवामान रस्ता जोडणी प्रदान करणे आहे.', 'All-weather road connectivity to rural areas, improved access to markets and services.', 'ग्रामीण क्षेत्रों को सभी मौसम वाली सड़क कनेक्टिविटी, बाजारों और सेवाओं तक बेहतर पहुंच।', 'ग्रामीण भागांना सर्व-हवामान रस्ता जोडणी, बाजारपेठा आणि सेवांपर्यंत सुधारित प्रवेश.', 'https://pmgsy.nic.in/', '2025-06-10 06:04:39'),
(18, 'Jal Jeevan Mission (JJM)', 'जल जीवन मिशन (जेजेएम)', 'जल जीवन मिशन (जेजेएम)', 'Aims to provide safe and adequate drinking water through individual household tap connections by 2024 to all households in rural India.', 'ग्रामीण भारत में 2024 तक सभी घरों में व्यक्तिगत घरेलू नल कनेक्शन के माध्यम से सुरक्षित और पर्याप्त पेयजल प्रदान करना है।', 'ग्रामीण भारतातील सर्व घरांना 2024 पर्यंत वैयक्तिक घरगुती नळाच्या जोडण्यांद्वारे सुरक्षित आणि पुरेसे पिण्याचे पाणी उपलब्ध करून देणे आहे.', 'Assured tap water supply, improved health and hygiene.', 'सुनिश्चित नल जल आपूर्ति, बेहतर स्वास्थ्य और स्वच्छता।', 'खात्रीशीर नळ पाणीपुरवठा, सुधारित आरोग्य आणि स्वच्छता.', 'https://jaljeevanmission.gov.in/', '2025-06-10 06:04:39'),
(19, 'National Health Mission (NHM)', 'राष्ट्रीय स्वास्थ्य मिशन (एनएचएम)', 'राष्ट्रीय आरोग्य अभियान (एनएचएम)', 'Encompasses two sub-missions, the National Rural Health Mission (NRHM) and the National Urban Health Mission (NUHM). It aims to achieve universal access to equitable, affordable & quality healthcare services.', 'दो उप-मिशन, राष्ट्रीय ग्रामीण स्वास्थ्य मिशन (एनआरएचएम) और राष्ट्रीय शहरी स्वास्थ्य मिशन (एनयूएचएम) शामिल हैं। इसका उद्देश्य न्यायसंगत, सस्ती और गुणवत्तापूर्ण स्वास्थ्य सेवाओं तक सार्वभौमिक पहुंच प्राप्त करना है।', 'दोन उप-अभियाने, राष्ट्रीय ग्रामीण आरोग्य अभियान (एनआरएचएम) आणि राष्ट्रीय शहरी आरोग्य अभियान (एनयूएचएम) समाविष्ट करते. याचा उद्देश न्यायसंगत, परवडणाऱ्या आणि गुणवत्तापूर्ण आरोग्य सेवांपर्यंत सार्वत्रिक पोहोच मिळवणे आहे.', 'Improved access to healthcare, maternal and child health services, disease control.', 'स्वास्थ्य सेवा तक बेहतर पहुंच, मातृ एवं शिशु स्वास्थ्य सेवाएं, रोग नियंत्रण।', 'आरोग्य सेवेपर्यंत सुधारित पोहोच, माता आणि बाल आरोग्य सेवा, रोग नियंत्रण.', 'https://nhm.gov.in/', '2025-06-10 06:04:39'),
(20, 'Beti Bachao Beti Padhao (BBBP)', 'बेटी बचाओ बेटी पढ़ाओ (बीबीबीपी)', 'बेटी बचाओ बेटी पढाओ (बीबीबीपी)', 'Aims to address the issue of declining Child Sex Ratio (CSR) and related issues of empowerment of women through a life cycle continuum.', 'घटते बाल लिंग अनुपात (सीएसआर) और महिलाओं के सशक्तिकरण से संबंधित मुद्दों को एक जीवन चक्र निरंतरता के माध्यम से संबोधित करना है।', 'घटत्या बाल लिंग गुणोत्तराचा (सीएसआर) आणि महिलांच्या सक्षमीकरणाशी संबंधित मुद्द्यांचा जीवन चक्र निरंतरतेद्वारे सामना करणे आहे.', 'Prevention of gender biased sex selective elimination, ensuring survival and protection of the girl child, ensuring education and participation of the girl child.', 'लिंग-आधारित लिंग चयनात्मक उन्मूलन की रोकथाम, बालिका का अस्तित्व और संरक्षण सुनिश्चित करना, बालिका की शिक्षा और भागीदारी सुनिश्चित करना।', 'लिंग-आधारित लिंग निवडक निर्मूलन प्रतिबंध, मुलीच्या अस्तित्वाची आणि संरक्षणाची खात्री करणे, मुलीच्या शिक्षणाची आणि सहभागाची खात्री करणे.', 'https://wcd.nic.in/schemes/beti-bachao-beti-padhao-bbbp', '2025-06-10 06:04:39'),
(21, 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY) 4.0', 'प्रधानमंत्री कौशल विकास योजना (पीएमकेवीवाय) 4.0', 'प्रधानमंत्री कौशल्य विकास योजना (पीएमकेवीवाय) 4.0', 'The latest phase of the PMKVY scheme, focusing on industry-relevant skill training for Indian youth.', 'पीएमकेवीवाय योजना का नवीनतम चरण, भारतीय युवाओं के लिए उद्योग-प्रासंगिक कौशल प्रशिक्षण पर ध्यान केंद्रित करना।', 'पीएमकेवीवाय योजनेचा नवीनतम टप्पा, भारतीय युवकांसाठी उद्योग-संबंधित कौशल्य प्रशिक्षणावर लक्ष केंद्रित करणे.', 'Skill training aligned with industry needs, entrepreneurship development, stipend support.', 'उद्योग की जरूरतों के साथ संरेखित कौशल प्रशिक्षण, उद्यमिता विकास, वजीफा सहायता।', 'उद्योग गरजांशी सुसंगत कौशल्य प्रशिक्षण, उद्योजकता विकास, विद्यावेतन समर्थन.', 'https://pmkvyofficial.org/', '2025-06-10 06:04:39'),
(22, 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)', 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाई)', 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाय)', 'World’s largest health insurance scheme fully financed by the government that aims to provide a health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.', 'दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना जो सरकार द्वारा पूरी तरह से वित्तपोषित है, जिसका उद्देश्य द्वितीयक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर प्रदान करना है।', 'जगातील सर्वात मोठी आरोग्य विमा योजना जी शासनाद्वारे पूर्णपणे वित्तपुरवठा केली जाते, ज्याचा उद्देश द्वितीयक आणि तृतीयक काळजीसाठी प्रति कुटुंब प्रति वर्ष 5 लाख रुपयांचे आरोग्य कवच प्रदान करणे आहे.', 'Health cover of Rs. 5 lakhs per family per year, cashless access to healthcare services.', 'प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर, स्वास्थ्य सेवाओं तक कैशलेस पहुंच।', 'प्रति कुटुंब प्रति वर्ष 5 लाख रुपयांचे आरोग्य कवच, आरोग्य सेवांसाठी कॅशलेस प्रवेश.', 'https://pmjay.gov.in/', '2025-06-10 06:14:14'),
(23, 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)', 'प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)', 'प्रधानमंत्री किसान सन्मान निधी (पीएम-किसान)', 'An initiative by the Government of India to provide income support to all eligible farmer families across the country.', 'भारत सरकार द्वारा देश भर के सभी पात्र किसान परिवारों को आय सहायता प्रदान करने की एक पहल।', 'भारत सरकारची देशभरातील सर्व पात्र शेतकरी कुटुंबांना उत्पन्न समर्थन प्रदान करण्याची एक पहल.', 'Financial benefit of Rs. 6,000 per year in three equal installments of Rs. 2,000 each.', 'प्रति वर्ष 6,000 रुपये का वित्तीय लाभ, 2,000 रुपये की तीन समान किस्तों में।', 'प्रति वर्ष 6,000 रुपयांचा आर्थिक लाभ, प्रत्येक 2,000 रुपयांच्या तीन समान हप्त्यांमध्ये.', 'https://pmkisan.gov.in/', '2025-06-10 06:14:14'),
(24, 'Stand-Up India Scheme', 'स्टैंड-अप इंडिया योजना', 'स्टँड-अप इंडिया योजना', 'Facilitates bank loans between Rs 10 lakh and Rs 1 crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.', 'कम से कम एक अनुसूचित जाति (एससी) या अनुसूचित जनजाति (एसटी) उधारकर्ता और प्रति बैंक शाखा में कम से कम एक महिला उधारकर्ता को नई उद्यम स्थापित करने के लिए 10 लाख रुपये से 1 करोड़ रुपये के बीच बैंक ऋण की सुविधा प्रदान करता है।', 'नवीन उद्योग सुरू करण्यासाठी प्रत्येक बँक शाखेत किमान एक अनुसूचित जाती (एससी) किंवा अनुसूचित जमाती (एसटी) कर्जदार आणि किमान एक महिला कर्जदार यांना 10 लाख ते 1 कोटी रुपयांपर्यंतचे बँक कर्ज सुलभ करते.', 'Bank loans for greenfield projects, focus on SC/ST and women entrepreneurs.', 'नए परियोजनाओं के लिए बैंक ऋण, एससी/एसटी और महिला उद्यमियों पर ध्यान।', 'नवीन प्रकल्पांसाठी बँक कर्ज, एससी/एसटी आणि महिला उद्योजकांवर लक्ष केंद्रित.', 'https://www.standupmitra.in/', '2025-06-10 06:14:14'),
(25, 'Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM)', 'प्रधानमंत्री श्रम योगी मान-धन (पीएम-एसवाईएम)', 'प्रधानमंत्री श्रम योगी मान-धन (पीएम-एसवायएम)', 'A voluntary and contributory pension scheme for unorganised workers.', 'असंगठित श्रमिकों के लिए एक स्वैच्छिक और अंशदायी पेंशन योजना।', 'असंघटित कामगारांसाठी एक ऐच्छिक आणि अंशदायी निवृत्ती वेतन योजना.', 'Minimum assured pension of Rs 3000 per month after attaining the age of 60 years.', '60 वर्ष की आयु प्राप्त करने के बाद प्रति माह 3000 रुपये की न्यूनतम सुनिश्चित पेंशन।', '60 वर्षांचे वय पूर्ण झाल्यावर प्रति महिना 3000 रुपयांचे किमान सुनिश्चित निवृत्ती वेतन.', 'https://maandhan.in/shramyogi', '2025-06-10 06:14:14'),
(26, 'Saur Sujala Yojana', 'सौर सुजला योजना', 'सौर सुजला योजना', 'A scheme to provide subsidized solar-powered irrigation pumps to farmers.', 'किसानों को रियायती सौर ऊर्जा संचालित सिंचाई पंप प्रदान करने की एक योजना।', 'शेतकऱ्यांना अनुदानित सौर ऊर्जा-आधारित सिंचन पंप प्रदान करण्याची एक योजना.', 'Access to reliable irrigation, reduced electricity costs, environmental benefits.', 'विश्वसनीय सिंचाई तक पहुंच, बिजली की लागत में कमी, पर्यावरणीय लाभ।', 'विश्वसनीय सिंचनासाठी प्रवेश, कमी वीज खर्च, पर्यावरणीय लाभ.', 'https://mnre.gov.in/solar/solar-pumps/', '2025-06-10 06:14:14'),
(27, 'National Food Security Act (NFSA)', 'राष्ट्रीय खाद्य सुरक्षा अधिनियम (एनएफएसए)', 'राष्ट्रीय अन्न सुरक्षा अधिनियम (एनएफएसए)', 'Aims to provide subsidized food grains to approximately two-thirds of the population.', 'जनसंख्या के लगभग दो-तिहाई हिस्से को रियायती खाद्यान्न प्रदान करना है।', 'लोकसंख्येच्या सुमारे दोन-तृतीयांश भागाला अनुदानित अन्नधान्य प्रदान करणे आहे.', 'Highly subsidized food grains (rice, wheat, coarse grains).', 'अत्यधिक रियायती खाद्यान्न (चावल, गेहूं, मोटे अनाज)।', 'अत्यंत अनुदानित अन्नधान्य (तांदूळ, गहू, भरड धान्य).', 'https://nfsa.gov.in/', '2025-06-10 06:14:14'),
(28, 'Pradhan Mantri Fasal Bima Yojana (PMFBY)', 'प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाय)', 'प्रधानमंत्री पीक विमा योजना (पीएमएफबीवाय)', 'Provides comprehensive insurance coverage against failure of crops thereby helping in stabilizing the income of farmers.', 'फसलों की विफलता के खिलाफ व्यापक बीमा कवरेज प्रदान करता है जिससे किसानों की आय को स्थिर करने में मदद मिलती है।', 'पिकांच्या नुकसानीविरुद्ध व्यापक विमा संरक्षण प्रदान करते, ज्यामुळे शेतकऱ्यांचे उत्पन्न स्थिर करण्यास मदत होते.', 'Financial support to farmers, risk mitigation for crop failure.', 'किसानों को वित्तीय सहायता, फसल विफलता के लिए जोखिम कम करना।', 'शेतकऱ्यांना आर्थिक सहाय्य, पीक नुकसानीसाठी जोखीम कमी करणे.', 'https://pmfby.gov.in/', '2025-06-10 06:14:14'),
(29, 'Skill India Mission (Pradhan Mantri Kaushal Vikas Yojana - PMKVY)', 'स्किल इंडिया मिशन (प्रधानमंत्री कौशल विकास योजना - पीएमकेवीवाय)', 'स्किल इंडिया मिशन (प्रधानमंत्री कौशल्य विकास योजना - पीएमकेवीवाय)', 'Aims to train 40 crore people in India in different skills by 2022.', '2022 तक भारत में 40 करोड़ लोगों को विभिन्न कौशलों में प्रशिक्षित करना है।', '2022 पर्यंत भारतातील 40 कोटी लोकांना विविध कौशल्यांमध्ये प्रशिक्षित करणे आहे.', 'Skill training, certification, and placement assistance.', 'कौशल प्रशिक्षण, प्रमाणन और प्लेसमेंट सहायता।', 'कौशल प्रशिक्षण, प्रमाणपत्र आणि प्लेसमेंट सहाय्य.', 'https://pmkvyofficial.org/', '2025-06-10 06:14:14'),
(30, 'National Rural Livelihoods Mission (NRLM)', 'राष्ट्रीय ग्रामीण आजीविका मिशन (एनआरएलएम)', 'राष्ट्रीय ग्रामीण उपजीविका अभियान (एनआरएलएम)', 'A poverty alleviation project implemented by the Ministry of Rural Development, Government of India. It aims at promoting self-employment and organization of rural poor into Self Help Groups (SHGs).', 'भारत सरकार के ग्रामीण विकास मंत्रालय द्वारा कार्यान्वित एक गरीबी उन्मूलन परियोजना। इसका उद्देश्य ग्रामीण गरीबों को स्वयं सहायता समूहों (एसएचजी) में स्वयं-रोजगार और संगठन को बढ़ावा देना है।', 'भारत सरकारच्या ग्रामीण विकास मंत्रालयाद्वारे कार्यान्वित केलेला एक दारिद्र्य निर्मूलन प्रकल्प. याचा उद्देश ग्रामीण गरिबांना स्वयं-रोजगार आणि स्वयं-सहायता गटांमध्ये (एसएचजी) संघटित करणे आहे.', 'Support for Self Help Groups, financial assistance, skill development for livelihood activities.', 'स्वयं सहायता समूहों के लिए समर्थन, वित्तीय सहायता, आजीविका गतिविधियों के लिए कौशल विकास।', 'स्वयं-सहायता गटांना समर्थन, आर्थिक सहाय्य, उपजीविका कार्यांसाठी कौशल्य विकास.', 'https://nrlm.gov.in/', '2025-06-10 06:14:14'),
(31, 'Swachh Bharat Abhiyan (SBA)', 'स्वच्छ भारत अभियान (एसबीए)', 'स्वच्छ भारत अभियान (एसबीए)', 'A nationwide campaign in India for the period 2014 to 2019 that aims to clean up the streets, roads, and infrastructure of India’s cities, towns, and rural areas.', '2014 से 2019 की अवधि के लिए भारत में एक राष्ट्रव्यापी अभियान जिसका उद्देश्य भारत के शहरों, कस्बों और ग्रामीण क्षेत्रों की सड़कों, सड़कों और बुनियादी ढांचे को साफ करना है।', '2014 ते 2019 या कालावधीसाठी भारतातील एक देशव्यापी मोहीम ज्याचा उद्देश भारतातील शहरे, शहरे आणि ग्रामीण भागातील रस्ते, रस्ते आणि पायाभूत सुविधा स्वच्छ करणे आहे.', 'Improved sanitation, waste management, public health benefits.', 'बेहतर स्वच्छता, अपशिष्ट प्रबंधन, सार्वजनिक स्वास्थ्य लाभ।', 'सुधारित स्वच्छता, कचरा व्यवस्थापन, सार्वजनिक आरोग्याचे फायदे.', 'https://swachhbharatmission.gov.in/', '2025-06-10 06:14:14'),
(32, 'Pradhan Mantri Gram Sadak Yojana (PMGSY)', 'प्रधानमंत्री ग्राम सड़क योजना (पीएमजीएसवाई)', 'प्रधानमंत्री ग्राम सडक योजना (पीएमजीएसवाय)', 'A nationwide plan in India to provide good all-weather road connectivity to unconnected habitations.', 'भारत में एक राष्ट्रव्यापी योजना जिसका उद्देश्य असंबंधित बस्तियों को अच्छी सभी मौसम वाली सड़क कनेक्टिविटी प्रदान करना है।', 'भारतातील एक देशव्यापी योजना ज्याचा उद्देश असंबंधित वस्त्यांना चांगली सर्व-हवामान रस्ता जोडणी प्रदान करणे आहे.', 'All-weather road connectivity to rural areas, improved access to markets and services.', 'ग्रामीण क्षेत्रों को सभी मौसम वाली सड़क कनेक्टिविटी, बाजारों और सेवाओं तक बेहतर पहुंच।', 'ग्रामीण भागांना सर्व-हवामान रस्ता जोडणी, बाजारपेठा आणि सेवांपर्यंत सुधारित प्रवेश.', 'https://pmgsy.nic.in/', '2025-06-10 06:14:14'),
(33, 'Jal Jeevan Mission (JJM)', 'जल जीवन मिशन (जेजेएम)', 'जल जीवन मिशन (जेजेएम)', 'Aims to provide safe and adequate drinking water through individual household tap connections by 2024 to all households in rural India.', 'ग्रामीण भारत में 2024 तक सभी घरों में व्यक्तिगत घरेलू नल कनेक्शन के माध्यम से सुरक्षित और पर्याप्त पेयजल प्रदान करना है।', 'ग्रामीण भारतातील सर्व घरांना 2024 पर्यंत वैयक्तिक घरगुती नळाच्या जोडण्यांद्वारे सुरक्षित आणि पुरेसे पिण्याचे पाणी उपलब्ध करून देणे आहे.', 'Assured tap water supply, improved health and hygiene.', 'सुनिश्चित नल जल आपूर्ति, बेहतर स्वास्थ्य और स्वच्छता।', 'खात्रीशीर नळ पाणीपुरवठा, सुधारित आरोग्य आणि स्वच्छता.', 'https://jaljeevanmission.gov.in/', '2025-06-10 06:14:14'),
(34, 'National Health Mission (NHM)', 'राष्ट्रीय स्वास्थ्य मिशन (एनएचएम)', 'राष्ट्रीय आरोग्य अभियान (एनएचएम)', 'Encompasses two sub-missions, the National Rural Health Mission (NRHM) and the National Urban Health Mission (NUHM). It aims to achieve universal access to equitable, affordable & quality healthcare services.', 'दो उप-मिशन, राष्ट्रीय ग्रामीण स्वास्थ्य मिशन (एनआरएचएम) और राष्ट्रीय शहरी स्वास्थ्य मिशन (एनयूएचएम) शामिल हैं। इसका उद्देश्य न्यायसंगत, सस्ती और गुणवत्तापूर्ण स्वास्थ्य सेवाओं तक सार्वभौमिक पहुंच प्राप्त करना है।', 'दोन उप-अभियाने, राष्ट्रीय ग्रामीण आरोग्य अभियान (एनआरएचएम) आणि राष्ट्रीय शहरी आरोग्य अभियान (एनयूएचएम) समाविष्ट करते. याचा उद्देश न्यायसंगत, परवडणाऱ्या आणि गुणवत्तापूर्ण आरोग्य सेवांपर्यंत सार्वत्रिक पोहोच मिळवणे आहे.', 'Improved access to healthcare, maternal and child health services, disease control.', 'स्वास्थ्य सेवा तक बेहतर पहुंच, मातृ एवं शिशु स्वास्थ्य सेवाएं, रोग नियंत्रण।', 'आरोग्य सेवेपर्यंत सुधारित पोहोच, माता आणि बाल आरोग्य सेवा, रोग नियंत्रण.', 'https://nhm.gov.in/', '2025-06-10 06:14:14'),
(35, 'Beti Bachao Beti Padhao (BBBP)', 'बेटी बचाओ बेटी पढ़ाओ (बीबीबीपी)', 'बेटी बचाओ बेटी पढाओ (बीबीबीपी)', 'Aims to address the issue of declining Child Sex Ratio (CSR) and related issues of empowerment of women through a life cycle continuum.', 'घटते बाल लिंग अनुपात (सीएसआर) और महिलाओं के सशक्तिकरण से संबंधित मुद्दों को एक जीवन चक्र निरंतरता के माध्यम से संबोधित करना है।', 'घटत्या बाल लिंग गुणोत्तराचा (सीएसआर) आणि महिलांच्या सक्षमीकरणाशी संबंधित मुद्द्यांचा जीवन चक्र निरंतरतेद्वारे सामना करणे आहे.', 'Prevention of gender biased sex selective elimination, ensuring survival and protection of the girl child, ensuring education and participation of the girl child.', 'लिंग-आधारित लिंग चयनात्मक उन्मूलन की रोकथाम, बालिका का अस्तित्व और संरक्षण सुनिश्चित करना, बालिका की शिक्षा और भागीदारी सुनिश्चित करना।', 'लिंग-आधारित लिंग निवडक निर्मूलन प्रतिबंध, मुलीच्या अस्तित्वाची आणि संरक्षणाची खात्री करणे, मुलीच्या शिक्षणाची आणि सहभागाची खात्री करणे.', 'https://wcd.nic.in/schemes/beti-bachao-beti-padhao-bbbp', '2025-06-10 06:14:14'),
(36, 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY) 4.0', 'प्रधानमंत्री कौशल विकास योजना (पीएमकेवीवाय) 4.0', 'प्रधानमंत्री कौशल्य विकास योजना (पीएमकेवीवाय) 4.0', 'The latest phase of the PMKVY scheme, focusing on industry-relevant skill training for Indian youth.', 'पीएमकेवीवाय योजना का नवीनतम चरण, भारतीय युवाओं के लिए उद्योग-प्रासंगिक कौशल प्रशिक्षण पर ध्यान केंद्रित करना।', 'पीएमकेवीवाय योजनेचा नवीनतम टप्पा, भारतीय युवकांसाठी उद्योग-संबंधित कौशल्य प्रशिक्षणावर लक्ष केंद्रित करणे.', 'Skill training aligned with industry needs, entrepreneurship development, stipend support.', 'उद्योग की जरूरतों के साथ संरेखित कौशल प्रशिक्षण, उद्यमिता विकास, वजीफा सहायता।', 'उद्योग गरजांशी सुसंगत कौशल्य प्रशिक्षण, उद्योजकता विकास, विद्यावेतन समर्थन.', 'https://pmkvyofficial.org/', '2025-06-10 06:14:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `schemes`
--
ALTER TABLE `schemes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `schemes`
--
ALTER TABLE `schemes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
